### ISSUE TITLE
Stat tracker

### ISSUE THREAD

**Issue by Thabb** [Thabb/DSA-Walker#12]
- [ ] This is an own menu (C)
- [ ] Players can create a new Stat object and can give it a value (string)
- [ ] The value is changable afterwards
