### ISSUE TITLE
Inventory tracker

### ISSUE THREAD

**Issue by Thabb** [Thabb/DSA-Walker#13]
- [ ] This is an own menu (I)
- [ ] Melee Weapon: Weight, Value, Damage, Attack, Parade, Damagebonus
- [ ] Ranged Weapon: Weight, Value, Damage, Attack, Damagebonus, Ammunition
- [ ] Armor: Weight, Value, Protectionvalue, Burden
- [ ] Miscellaneous: Weight, Value, Amount
